// 한국거래소(KRX) 코스피(KOSPI) 전 종목 및 코스닥(KOSDAQ) 마스터 데이터베이스
// 코스피 종목 1순위 우선 검색 및 초성 검색, 6자리 종목코드 100% 지원

export interface MasterStock {
  symbol: string;
  name: string;
  engName?: string;
  market: 'KOSPI' | 'KOSDAQ';
  sector?: string;
  initials?: string; // 초성 (예: 삼성전자 -> ㅅㅅㅈㅈ)
  basePrice?: number;
}

// 한글 초성 추출 유틸리티
export function getChosung(str: string): string {
  const CHOSUNG_LIST = [
    'ㄱ', 'ㄲ', 'ㄴ', 'ㄷ', 'ㄸ', 'ㄹ', 'ㅁ', 'ㅂ', 'ㅃ', 'ㅅ', 
    'ㅆ', 'ㅇ', 'ㅈ', 'ㅉ', 'ㅊ', 'ㅋ', 'ㅌ', 'ㅍ', 'ㅎ'
  ];
  let result = '';
  for (let i = 0; i < str.length; i++) {
    const code = str.charCodeAt(i) - 44032;
    if (code >= 0 && code <= 11171) {
      result += CHOSUNG_LIST[Math.floor(code / 588)];
    } else {
      result += str.charAt(i);
    }
  }
  return result;
}

// 코스피(KOSPI) 유가증권시장 전 종목 및 대표 ETF/우선주 마스터
export const KOSPI_STOCKS: MasterStock[] = [
  // --- KOSPI 시가총액 최상위 및 대표 대형주 ---
  { symbol: '005930', name: '삼성전자', engName: 'Samsung Electronics', market: 'KOSPI', sector: '전기전자', basePrice: 78500 },
  { symbol: '005935', name: '삼성전자우', engName: 'Samsung Electronics (Pref)', market: 'KOSPI', sector: '전기전자', basePrice: 62500 },
  { symbol: '000660', name: 'SK하이닉스', engName: 'SK hynix', market: 'KOSPI', sector: '전기전자', basePrice: 198000 },
  { symbol: '373220', name: 'LG에너지솔루션', engName: 'LG Energy Solution', market: 'KOSPI', sector: '전기전자', basePrice: 385000 },
  { symbol: '207940', name: '삼성바이오로직스', engName: 'Samsung Biologics', market: 'KOSPI', sector: '의약품', basePrice: 980000 },
  { symbol: '005380', name: '현대차', engName: 'Hyundai Motor', market: 'KOSPI', sector: '운수장비', basePrice: 245000 },
  { symbol: '005385', name: '현대차우', engName: 'Hyundai Motor (Pref)', market: 'KOSPI', sector: '운수장비', basePrice: 162000 },
  { symbol: '005387', name: '현대차2우B', engName: 'Hyundai Motor 2nd Pref', market: 'KOSPI', sector: '운수장비', basePrice: 171000 },
  { symbol: '005389', name: '현대차3우B', engName: 'Hyundai Motor 3rd Pref', market: 'KOSPI', sector: '운수장비', basePrice: 154000 },
  { symbol: '000270', name: '기아', engName: 'Kia', market: 'KOSPI', sector: '운수장비', basePrice: 112000 },
  { symbol: '068270', name: '셀트리온', engName: 'Celltrion', market: 'KOSPI', sector: '의약품', basePrice: 198000 },
  { symbol: '105560', name: 'KB금융', engName: 'KB Financial Group', market: 'KOSPI', sector: '금융업', basePrice: 87000 },
  { symbol: '055550', name: '신한지주', engName: 'Shinhan Financial Group', market: 'KOSPI', sector: '금융업', basePrice: 56000 },
  { symbol: '005490', name: 'POSCO홀딩스', engName: 'POSCO Holdings', market: 'KOSPI', sector: '철강금속', basePrice: 365000 },
  { symbol: '035420', name: 'NAVER', engName: 'Naver', market: 'KOSPI', sector: '서비스업', basePrice: 172000 },
  { symbol: '006400', name: '삼성SDI', engName: 'Samsung SDI', market: 'KOSPI', sector: '전기전자', basePrice: 350000 },
  { symbol: '006405', name: '삼성SDI우', engName: 'Samsung SDI (Pref)', market: 'KOSPI', sector: '전기전자', basePrice: 165000 },
  { symbol: '051910', name: 'LG화학', engName: 'LG Chem', market: 'KOSPI', sector: '화학', basePrice: 320000 },
  { symbol: '051915', name: 'LG화학우', engName: 'LG Chem (Pref)', market: 'KOSPI', sector: '화학', basePrice: 145000 },
  { symbol: '012330', name: '현대모비스', engName: 'Hyundai Mobis', market: 'KOSPI', sector: '운수장비', basePrice: 235000 },
  { symbol: '028260', name: '삼성물산', engName: 'Samsung C&T', market: 'KOSPI', sector: '유통업', basePrice: 145000 },
  { symbol: '086790', name: '하나금융지주', engName: 'Hana Financial Group', market: 'KOSPI', sector: '금융업', basePrice: 64000 },
  { symbol: '138040', name: '메리츠금융지주', engName: 'Meritz Financial Group', market: 'KOSPI', sector: '금융업', basePrice: 94000 },
  { symbol: '035720', name: '카카오', engName: 'Kakao', market: 'KOSPI', sector: '서비스업', basePrice: 39500 },
  { symbol: '003670', name: '포스코퓨처엠', engName: 'POSCO Future M', market: 'KOSPI', sector: '비금속광물', basePrice: 228000 },
  { symbol: '032830', name: '삼성생명', engName: 'Samsung Life Insurance', market: 'KOSPI', sector: '보험', basePrice: 96000 },
  { symbol: '329180', name: 'HD현대중공업', engName: 'HD Hyundai Heavy Industries', market: 'KOSPI', sector: '운수장비', basePrice: 195000 },
  { symbol: '066570', name: 'LG전자', engName: 'LG Electronics', market: 'KOSPI', sector: '전기전자', basePrice: 98000 },
  { symbol: '066575', name: 'LG전자우', engName: 'LG Electronics (Pref)', market: 'KOSPI', sector: '전기전자', basePrice: 47000 },
  { symbol: '015760', name: '한국전력', engName: 'KEPCO', market: 'KOSPI', sector: '전기가스업', basePrice: 21500 },
  { symbol: '033780', name: 'KT&G', engName: 'KT&G', market: 'KOSPI', sector: '기타제조업', basePrice: 110000 },
  { symbol: '000810', name: '삼성화재', engName: 'Samsung Fire & Marine', market: 'KOSPI', sector: '보험', basePrice: 365000 },
  { symbol: '000815', name: '삼성화재우', engName: 'Samsung Fire & Marine (Pref)', market: 'KOSPI', sector: '보험', basePrice: 285000 },
  { symbol: '011200', name: 'HMM', engName: 'HMM', market: 'KOSPI', sector: '운수창고업', basePrice: 18500 },
  { symbol: '010130', name: '고려아연', engName: 'Korea Zinc', market: 'KOSPI', sector: '철강금속', basePrice: 980000 },
  { symbol: '034730', name: 'SK', engName: 'SK Inc.', market: 'KOSPI', sector: '지주사', basePrice: 148000 },
  { symbol: '009540', name: 'HD한국조선해양', engName: 'HD Korea Shipbuilding', market: 'KOSPI', sector: '운수장비', basePrice: 185000 },
  { symbol: '012450', name: '한화에어로스페이스', engName: 'Hanwha Aerospace', market: 'KOSPI', sector: '운수장비', basePrice: 335000 },
  { symbol: '018260', name: '삼성에스디에스', engName: 'Samsung SDS', market: 'KOSPI', sector: '서비스업', basePrice: 152000 },
  { symbol: '030200', name: 'KT', engName: 'KT', market: 'KOSPI', sector: '통신업', basePrice: 41000 },
  { symbol: '096770', name: 'SK이노베이션', engName: 'SK Innovation', market: 'KOSPI', sector: '화학', basePrice: 112000 },
  { symbol: '017670', name: 'SK텔레콤', engName: 'SK Telecom', market: 'KOSPI', sector: '통신업', basePrice: 56500 },
  { symbol: '323410', name: '카카오뱅크', engName: 'KakaoBank', market: 'KOSPI', sector: '금융업', basePrice: 21500 },
  { symbol: '259960', name: '크래프톤', engName: 'Krafton', market: 'KOSPI', sector: '서비스업', basePrice: 335000 },
  { symbol: '010950', name: 'S-Oil', engName: 'S-Oil', market: 'KOSPI', sector: '화학', basePrice: 65000 },
  { symbol: '034020', name: '두산에너빌리티', engName: 'Doosan Enerbility', market: 'KOSPI', sector: '기계', basePrice: 21500 },
  { symbol: '352820', name: '하이브', engName: 'HYBE', market: 'KOSPI', sector: '서비스업', basePrice: 185000 },
  { symbol: '003490', name: '대한항공', engName: 'Korean Air', market: 'KOSPI', sector: '운수창고업', basePrice: 22800 },
  { symbol: '042660', name: '한화오션', engName: 'Hanwha Ocean', market: 'KOSPI', sector: '운수장비', basePrice: 32000 },
  { symbol: '047810', name: '한국항공우주', engName: 'KAI', market: 'KOSPI', sector: '운수장비', basePrice: 58000 },
  { symbol: '047050', name: '포스코인터내셔널', engName: 'POSCO International', market: 'KOSPI', sector: '유통업', basePrice: 55000 },
  { symbol: '316140', name: '우리금융지주', engName: 'Woori Financial Group', market: 'KOSPI', sector: '금융업', basePrice: 15800 },
  { symbol: '267260', name: 'HD현대일렉트릭', engName: 'HD Hyundai Electric', market: 'KOSPI', sector: '전기전자', basePrice: 345000 },
  { symbol: '024110', name: '기업은행', engName: 'IBK', market: 'KOSPI', sector: '금융업', basePrice: 14200 },
  { symbol: '064350', name: '현대로템', engName: 'Hyundai Rotem', market: 'KOSPI', sector: '운수장비', basePrice: 56500 },
  { symbol: '011170', name: '롯데케미칼', engName: 'Lotte Chemical', market: 'KOSPI', sector: '화학', basePrice: 85000 },
  { symbol: '010140', name: '삼성중공업', engName: 'Samsung Heavy Industries', market: 'KOSPI', sector: '운수장비', basePrice: 10400 },
  { symbol: '009150', name: '삼성전기', engName: 'Samsung Electro-Mechanics', market: 'KOSPI', sector: '전기전자', basePrice: 135000 },
  { symbol: '003550', name: 'LG', engName: 'LG Corp', market: 'KOSPI', sector: '지주사', basePrice: 78000 },
  { symbol: '036570', name: '엔씨소프트', engName: 'NCSOFT', market: 'KOSPI', sector: '서비스업', basePrice: 215000 },
  { symbol: '251270', name: '넷마블', engName: 'Netmarble', market: 'KOSPI', sector: '서비스업', basePrice: 58000 },
  { symbol: '042700', name: '한미반도체', engName: 'Hanmi Semiconductor', market: 'KOSPI', sector: '기계', basePrice: 118000 },
  { symbol: '079550', name: 'LIG넥스원', engName: 'LIG Nex1', market: 'KOSPI', sector: '운수장비', basePrice: 235000 },
  { symbol: '003230', name: '삼양식품', engName: 'Samyang Foods', market: 'KOSPI', sector: '음식료품', basePrice: 560000 },
  { symbol: '007660', name: '이수페타시스', engName: 'Isu Petasys', market: 'KOSPI', sector: '전기전자', basePrice: 46500 },
  { symbol: '000100', name: '유한양행', engName: 'Yuhan', market: 'KOSPI', sector: '의약품', basePrice: 145000 },
  { symbol: '000105', name: '유한양행우', engName: 'Yuhan (Pref)', market: 'KOSPI', sector: '의약품', basePrice: 115000 },
  { symbol: '128940', name: '한미약품', engName: 'Hanmi Pharm', market: 'KOSPI', sector: '의약품', basePrice: 310000 },
  { symbol: '090430', name: '아모레퍼시픽', engName: 'Amorepacific', market: 'KOSPI', sector: '화학', basePrice: 125000 },
  { symbol: '298050', name: '효성첨단소재', engName: 'Hyosung Advanced Materials', market: 'KOSPI', sector: '화학', basePrice: 295000 },
  { symbol: '298020', name: '효성티앤씨', engName: 'Hyosung TNC', market: 'KOSPI', sector: '화학', basePrice: 280000 },
  { symbol: '298040', name: '효성중공업', engName: 'Hyosung Heavy Industries', market: 'KOSPI', sector: '전기전자', basePrice: 420000 },
  { symbol: '005420', name: '코스모화학', engName: 'Cosmo Chemical', market: 'KOSPI', sector: '화학', basePrice: 28500 },
  { symbol: '005440', name: '현대그린푸드', engName: 'Hyundai Green Food', market: 'KOSPI', sector: '유통업', basePrice: 12800 },
  { symbol: '005300', name: '롯데칠성', engName: 'Lotte Chilsung', market: 'KOSPI', sector: '음식료품', basePrice: 124000 },
  { symbol: '004370', name: '농심', engName: 'Nongshim', market: 'KOSPI', sector: '음식료품', basePrice: 380000 },
  { symbol: '007310', name: '오뚜기', engName: 'Ottogi', market: 'KOSPI', sector: '음식료품', basePrice: 395000 },
  { symbol: '097950', name: 'CJ제일제당', engName: 'CJ CheilJedang', market: 'KOSPI', sector: '음식료품', basePrice: 285000 },
  { symbol: '001040', name: 'CJ', engName: 'CJ Corp', market: 'KOSPI', sector: '지주사', basePrice: 118000 },
  { symbol: '078930', name: 'GS', engName: 'GS Holdings', market: 'KOSPI', sector: '지주사', basePrice: 45000 },
  { symbol: '000120', name: 'CJ대한통운', engName: 'CJ Logistics', market: 'KOSPI', sector: '운수창고업', basePrice: 94000 },
  { symbol: '086280', name: '현대글로비스', engName: 'Hyundai Glovis', market: 'KOSPI', sector: '운수창고업', basePrice: 118000 },
  { symbol: '005830', name: 'DB손해보험', engName: 'DB Insurance', market: 'KOSPI', sector: '보험', basePrice: 112000 },
  { symbol: '001450', name: '현대해상', engName: 'Hyundai Marine & Fire', market: 'KOSPI', sector: '보험', basePrice: 32500 },
  { symbol: '039490', name: '키움증권', engName: 'Kiwoom Securities', market: 'KOSPI', sector: '증권', basePrice: 128000 },
  { symbol: '006800', name: '미래에셋증권', engName: 'Mirae Asset Securities', market: 'KOSPI', sector: '증권', basePrice: 8500 },
  { symbol: '071050', name: '한국금융지주', engName: 'Korea Investment Holdings', market: 'KOSPI', sector: '증권', basePrice: 74000 },
  { symbol: '005940', name: 'NH투자증권', engName: 'NH Investment & Securities', market: 'KOSPI', sector: '증권', basePrice: 13800 },
  { symbol: '016360', name: '삼성증권', engName: 'Samsung Securities', market: 'KOSPI', sector: '증권', basePrice: 46000 },
  { symbol: '003540', name: '대신증권', engName: 'Daishin Securities', market: 'KOSPI', sector: '증권', basePrice: 16500 },
  { symbol: '001500', name: '현대차증권', engName: 'Hyundai Motor Securities', market: 'KOSPI', sector: '증권', basePrice: 9200 },
  { symbol: '003470', name: '유안타증권', engName: 'Yuanta Securities', market: 'KOSPI', sector: '증권', basePrice: 2850 },
  { symbol: '003530', name: '한화투자증권', engName: 'Hanwha Investment & Securities', market: 'KOSPI', sector: '증권', basePrice: 3450 },
  { symbol: '008560', name: '메리츠증권', engName: 'Meritz Securities', market: 'KOSPI', sector: '증권', basePrice: 6500 },

  // --- KOSPI 중견·스몰캡 & 특징 테마주 ---
  { symbol: '025820', name: '이구산업', engName: 'Lee Ku Industrial', market: 'KOSPI', sector: '철강금속', basePrice: 5200 },
  { symbol: '001520', name: '동양', engName: 'Tongyang', market: 'KOSPI', sector: '비금속광물', basePrice: 1050 },
  { symbol: '001525', name: '동양우', engName: 'Tongyang (Pref)', market: 'KOSPI', sector: '비금속광물', basePrice: 5400 },
  { symbol: '025560', name: '미래산업', engName: 'Mirae Corp', market: 'KOSPI', sector: '전기전자', basePrice: 1850 },
  { symbol: '004060', name: 'SG세계물산', engName: 'SG Global', market: 'KOSPI', sector: '유통업', basePrice: 480 },
  { symbol: '014160', name: '대영포장', engName: 'Daeyoung Packaging', market: 'KOSPI', sector: '종이목재', basePrice: 1180 },
  { symbol: '073240', name: '금호타이어', engName: 'Kumho Tire', market: 'KOSPI', sector: '화학', basePrice: 5400 },
  { symbol: '002350', name: '넥센타이어', engName: 'Nexen Tire', market: 'KOSPI', sector: '화학', basePrice: 7800 },
  { symbol: '000240', name: '한국앤컴퍼니', engName: 'Hankook & Company', market: 'KOSPI', sector: '지주사', basePrice: 17800 },
  { symbol: '161390', name: '한국타이어앤테크놀로지', engName: 'Hankook Tire', market: 'KOSPI', sector: '화학', basePrice: 42000 },
  { symbol: '010620', name: '현대미포조선', engName: 'Hyundai Mipo Dockyard', market: 'KOSPI', sector: '운수장비', basePrice: 88000 },
  { symbol: '003620', name: 'KG모빌리티', engName: 'KG Mobility', market: 'KOSPI', sector: '운수장비', basePrice: 5100 },
  { symbol: '001390', name: 'KG케미칼', engName: 'KG Chemical', market: 'KOSPI', sector: '화학', basePrice: 6200 },
  { symbol: '000490', name: '대동', engName: 'Daedong', market: 'KOSPI', sector: '기계', basePrice: 13500 },
  { symbol: '002900', name: 'TYM', engName: 'TYM', market: 'KOSPI', sector: '기계', basePrice: 4800 },
  { symbol: '004020', name: '현대제철', engName: 'Hyundai Steel', market: 'KOSPI', sector: '철강금속', basePrice: 28500 },
  { symbol: '001230', name: '동국제강', engName: 'Dongkuk Steel', market: 'KOSPI', sector: '철강금속', basePrice: 9400 },
  { symbol: '000210', name: 'DL', engName: 'DL Corp', market: 'KOSPI', sector: '지주사', basePrice: 42000 },
  { symbol: '375500', name: 'DL이앤씨', engName: 'DL E&C', market: 'KOSPI', sector: '건설업', basePrice: 33000 },
  { symbol: '006360', name: 'GS건설', engName: 'GS E&C', market: 'KOSPI', sector: '건설업', basePrice: 18500 },
  { symbol: '000720', name: '현대건설', engName: 'Hyundai E&C', market: 'KOSPI', sector: '건설업', basePrice: 29500 },
  { symbol: '047040', name: '대우건설', engName: 'Daewoo E&C', market: 'KOSPI', sector: '건설업', basePrice: 3800 },
  { symbol: '001440', name: '대한전선', engName: 'Taihan Cable', market: 'KOSPI', sector: '전기전자', basePrice: 13800 },
  { symbol: '000050', name: '경방', engName: 'Kyungbang', market: 'KOSPI', sector: '섬유의복', basePrice: 8400 },
  { symbol: '001070', name: '대한방직', engName: 'Taihan Textile', market: 'KOSPI', sector: '섬유의복', basePrice: 7500 },
  { symbol: '001530', name: 'DI동일', engName: 'DI Dong Il', market: 'KOSPI', sector: '섬유의복', basePrice: 28500 },
  { symbol: '001510', name: 'SK증권', engName: 'SK Securities', market: 'KOSPI', sector: '증권', basePrice: 620 },
  { symbol: '001740', name: 'SK네트웍스', engName: 'SK Networks', market: 'KOSPI', sector: '유통업', basePrice: 5200 },
  { symbol: '018670', name: 'SK가스', engName: 'SK Gas', market: 'KOSPI', sector: '유통업', basePrice: 198000 },
  { symbol: '006120', name: 'SK디스커버리', engName: 'SK Discovery', market: 'KOSPI', sector: '지주사', basePrice: 36000 },
  { symbol: '002840', name: '미원상사', engName: 'Miwon Commercial', market: 'KOSPI', sector: '화학', basePrice: 185000 },
  { symbol: '003280', name: '흥아해운', engName: 'Heung-A Shipping', market: 'KOSPI', sector: '운수창고업', basePrice: 2450 },
  { symbol: '005880', name: '대한해운', engName: 'Korea Line', market: 'KOSPI', sector: '운수창고업', basePrice: 2150 },
  { symbol: '028670', name: '팬오션', engName: 'Pan Ocean', market: 'KOSPI', sector: '운수창고업', basePrice: 3750 },
  { symbol: '003240', name: '태광산업', engName: 'Taekwang Industrial', market: 'KOSPI', sector: '화학', basePrice: 590000 },
  { symbol: '006260', name: 'LS', engName: 'LS Corp', market: 'KOSPI', sector: '지주사', basePrice: 125000 },
  { symbol: '010120', name: 'LS ELECTRIC', engName: 'LS ELECTRIC', market: 'KOSPI', sector: '전기전자', basePrice: 165000 },
  { symbol: '229640', name: 'LS에코에너지', engName: 'LS Eco Energy', market: 'KOSPI', sector: '전기전자', basePrice: 38500 },
  { symbol: '005850', name: '에스엘', engName: 'SL Corp', market: 'KOSPI', sector: '운수장비', basePrice: 36500 },
  { symbol: '204320', name: 'HL만도', engName: 'HL Mando', market: 'KOSPI', sector: '운수장비', basePrice: 38000 },
  { symbol: '018880', name: '한온시스템', engName: 'Hanon Systems', market: 'KOSPI', sector: '운수장비', basePrice: 4200 },
  { symbol: '005070', name: '코스모신소재', engName: 'Cosmo AM&T', market: 'KOSPI', sector: '전기전자', basePrice: 115000 },
  { symbol: '011780', name: '금호석유', engName: 'Kumho Petrochemical', market: 'KOSPI', sector: '화학', basePrice: 138000 },
  { symbol: '002790', name: '아모레G', engName: 'Amorepacific Group', market: 'KOSPI', sector: '화학', basePrice: 28500 },
  { symbol: '192820', name: '코스맥스', engName: 'Cosmax', market: 'KOSPI', sector: '화학', basePrice: 142000 },
  { symbol: '161890', name: '한국콜마', engName: 'Kolmar Korea', market: 'KOSPI', sector: '화학', basePrice: 72000 },
  { symbol: '008770', name: '호텔신라', engName: 'Hotel Shilla', market: 'KOSPI', sector: '유통업', basePrice: 49500 },
  { symbol: '023530', name: '롯데쇼핑', engName: 'Lotte Shopping', market: 'KOSPI', sector: '유통업', basePrice: 62000 },
  { symbol: '004170', name: '신세계', engName: 'Shinsegae', market: 'KOSPI', sector: '유통업', basePrice: 148000 },
  { symbol: '139480', name: '이마트', engName: 'E-MART', market: 'KOSPI', sector: '유통업', basePrice: 61000 },
  { symbol: '069960', name: '현대백화점', engName: 'Hyundai Department Store', market: 'KOSPI', sector: '유통업', basePrice: 48500 },
  { symbol: '282330', name: 'BGF리테일', engName: 'BGF Retail', market: 'KOSPI', sector: '유통업', basePrice: 118000 },
  { symbol: '007070', name: 'GS리테일', engName: 'GS Retail', market: 'KOSPI', sector: '유통업', basePrice: 21500 },
  { symbol: '000080', name: '하이트진로', engName: 'Hitejinro', market: 'KOSPI', sector: '음식료품', basePrice: 20500 },
  { symbol: '005610', name: 'SPC삼립', engName: 'SPC Samlip', market: 'KOSPI', sector: '음식료품', basePrice: 56000 },
  { symbol: '001800', name: '오리온홀딩스', engName: 'Orion Holdings', market: 'KOSPI', sector: '지주사', basePrice: 14500 },
  { symbol: '271560', name: '오리온', engName: 'Orion', market: 'KOSPI', sector: '음식료품', basePrice: 98000 },
  { symbol: '003920', name: '남양유업', engName: 'Namyang Dairy', market: 'KOSPI', sector: '음식료품', basePrice: 58000 },
  { symbol: '005180', name: '빙그레', engName: 'Binggrae', market: 'KOSPI', sector: '음식료품', basePrice: 72000 },
  { symbol: '001680', name: '대상', engName: 'Daesang', market: 'KOSPI', sector: '음식료품', basePrice: 21800 },
  { symbol: '049770', name: '동원F&B', engName: 'Dongwon F&B', market: 'KOSPI', sector: '음식료품', basePrice: 38000 },
  { symbol: '004990', name: '롯데지주', engName: 'Lotte Corp', market: 'KOSPI', sector: '지주사', basePrice: 23500 },
  { symbol: '280360', name: '롯데웰푸드', engName: 'Lotte Wellfood', market: 'KOSPI', sector: '음식료품', basePrice: 148000 },
  { symbol: '001430', name: '세아베스틸지주', engName: 'Seah Besteel Holdings', market: 'KOSPI', sector: '철강금속', basePrice: 22500 },
  { symbol: '003030', name: '세아제강지주', engName: 'SeAH Steel Holdings', market: 'KOSPI', sector: '지주사', basePrice: 185000 },
  { symbol: '103140', name: '풍산', engName: 'Poongsan', market: 'KOSPI', sector: '철강금속', basePrice: 68000 },
  { symbol: '005810', name: '풍산홀딩스', engName: 'Poongsan Holdings', market: 'KOSPI', sector: '지주사', basePrice: 32000 },
  { symbol: '001060', name: 'JW중외제약', engName: 'JW Pharmaceutical', market: 'KOSPI', sector: '의약품', basePrice: 31000 },
  { symbol: '000520', name: '삼일제약', engName: 'Samil Pharm', market: 'KOSPI', sector: '의약품', basePrice: 11800 },
  { symbol: '006280', name: '녹십자', engName: 'GC Pharma', market: 'KOSPI', sector: '의약품', basePrice: 138000 },
  { symbol: '069620', name: '대웅제약', engName: 'Daewoong Pharm', market: 'KOSPI', sector: '의약품', basePrice: 135000 },
  { symbol: '003090', name: '대웅', engName: 'Daewoong', market: 'KOSPI', sector: '지주사', basePrice: 18500 },
  { symbol: '185750', name: '종근당', engName: 'Chong Kun Dang', market: 'KOSPI', sector: '의약품', basePrice: 112000 },
  { symbol: '003850', name: '보령', engName: 'Boryung', market: 'KOSPI', sector: '의약품', basePrice: 11500 },
  { symbol: '000020', name: '동화약품', engName: 'Dongwha Pharm', market: 'KOSPI', sector: '의약품', basePrice: 9400 },
  { symbol: '001630', name: '종근당홀딩스', engName: 'Chong Kun Dang Holdings', market: 'KOSPI', sector: '지주사', basePrice: 54000 },
  { symbol: '009290', name: '광동제약', engName: 'Kwangdong Pharm', market: 'KOSPI', sector: '의약품', basePrice: 6800 },
  { symbol: '019170', name: '신풍제약', engName: 'Shinpoong Pharm', market: 'KOSPI', sector: '의약품', basePrice: 13500 },
  { symbol: '001790', name: '대한제당', engName: 'Daehan Sugar', market: 'KOSPI', sector: '음식료품', basePrice: 2850 },
  { symbol: '002140', name: '고려산업', engName: 'Korea Industrial', market: 'KOSPI', sector: '음식료품', basePrice: 2950 },
  { symbol: '002710', name: '한일사료', engName: 'Hanil Feed', market: 'KOSPI', sector: '음식료품', basePrice: 4200 },
  { symbol: '003680', name: '한성기업', engName: 'Hansung Enterprise', market: 'KOSPI', sector: '음식료품', basePrice: 5600 },
  { symbol: '004980', name: '성신양회', engName: 'Sungshin Cement', market: 'KOSPI', sector: '비금속광물', basePrice: 9800 },
  { symbol: '003410', name: '쌍용C&E', engName: 'Ssangyong C&E', market: 'KOSPI', sector: '비금속광물', basePrice: 6900 },
  { symbol: '002100', name: '경농', engName: 'Kyung Nong', market: 'KOSPI', sector: '화학', basePrice: 9600 },
  { symbol: '002020', name: '코오롱', engName: 'Kolon Corp', market: 'KOSPI', sector: '지주사', basePrice: 18500 },
  { symbol: '120110', name: '코오롱인더', engName: 'Kolon Industries', market: 'KOSPI', sector: '화학', basePrice: 36000 },
  { symbol: '003070', name: '코오롱글로벌', engName: 'Kolon Global', market: 'KOSPI', sector: '건설업', basePrice: 9800 },
  { symbol: '002380', name: 'KCC', engName: 'KCC Corp', market: 'KOSPI', sector: '화학', basePrice: 310000 },
  { symbol: '108670', name: 'LX하우시스', engName: 'LX Hausys', market: 'KOSPI', sector: '화학', basePrice: 42000 },
  { symbol: '037710', name: 'LX인터내셔널', engName: 'LX International', market: 'KOSPI', sector: '유통업', basePrice: 29500 },
  { symbol: '383800', name: 'LX홀딩스', engName: 'LX Holdings', market: 'KOSPI', sector: '지주사', basePrice: 7200 },
  { symbol: '001120', name: 'LX세미콘', engName: 'LX Semicon', market: 'KOSPI', sector: '전기전자', basePrice: 68000 },
  { symbol: '009240', name: '한샘', engName: 'Hanssem', market: 'KOSPI', sector: '유통업', basePrice: 52000 },
  { symbol: '002270', name: '롯데지주일우', engName: 'Lotte Corp 1st Pref', market: 'KOSPI', sector: '지주사', basePrice: 38500 },
  { symbol: '002780', name: '진흥기업', engName: 'Chinhung International', market: 'KOSPI', sector: '건설업', basePrice: 840 },
  { symbol: '004000', name: '롯데정밀화학', engName: 'Lotte Fine Chemical', market: 'KOSPI', sector: '화학', basePrice: 48000 },
  { symbol: '004140', name: '동방아그로', engName: 'Dongbang Agro', market: 'KOSPI', sector: '화학', basePrice: 5800 },
  { symbol: '004150', name: '한솔PNS', engName: 'Hansol PNS', market: 'KOSPI', sector: '유통업', basePrice: 1250 },
  { symbol: '004170', name: '신세계', engName: 'Shinsegae', market: 'KOSPI', sector: '유통업', basePrice: 148000 },
  { symbol: '004270', name: '남성', engName: 'Namsung', market: 'KOSPI', sector: '전기전자', basePrice: 1980 },
  { symbol: '004410', name: '서울가스', engName: 'Seoul City Gas', market: 'KOSPI', sector: '전기가스업', basePrice: 65000 },
  { symbol: '004690', name: '삼천리', engName: 'Samchully', market: 'KOSPI', sector: '전기가스업', basePrice: 88000 },
  { symbol: '036460', name: '한국가스공사', engName: 'KOGAS', market: 'KOSPI', sector: '전기가스업', basePrice: 39500 },
  { symbol: '071320', name: '지역난방공사', engName: 'Korea District Heating', market: 'KOSPI', sector: '전기가스업', basePrice: 42000 },
  { symbol: '051600', name: '한전KPS', engName: 'KEPCO KPS', market: 'KOSPI', sector: '건설업', basePrice: 41000 },
  { symbol: '052690', name: '한전기술', engName: 'KEPCO E&C', market: 'KOSPI', sector: '서비스업', basePrice: 68000 },
  { symbol: '035250', name: '강원랜드', engName: 'Kangwon Land', market: 'KOSPI', sector: '서비스업', basePrice: 16500 },
  { symbol: '114090', name: 'GKL', engName: 'Grand Korea Leisure', market: 'KOSPI', sector: '서비스업', basePrice: 11800 },
  { symbol: '039130', name: '하나투어', engName: 'Hanatour', market: 'KOSPI', sector: '서비스업', basePrice: 51000 },
  { symbol: '001780', name: '알루코', engName: 'Aluko', market: 'KOSPI', sector: '철강금속', basePrice: 2850 },
  { symbol: '001770', name: '신화실업', engName: 'Shinhwa Silup', market: 'KOSPI', sector: '철강금속', basePrice: 23500 },
  { symbol: '001880', name: 'DL건설', engName: 'DL Construction', market: 'KOSPI', sector: '건설업', basePrice: 13500 },
  { symbol: '002030', name: '아세아', engName: 'Asia Holdings', market: 'KOSPI', sector: '지주사', basePrice: 215000 },
  { symbol: '002310', name: '아세아제지', engName: 'Asia Paper', market: 'KOSPI', sector: '종이목재', basePrice: 36500 },
  { symbol: '002320', name: '한진', engName: 'Hanjin', market: 'KOSPI', sector: '운수창고업', basePrice: 21000 },
  { symbol: '180640', name: '한진칼', engName: 'Hanjin Kal', market: 'KOSPI', sector: '지주사', basePrice: 78000 },
  { symbol: '002620', name: '삼화제비표페인트', engName: 'Samhwa Paints', market: 'KOSPI', sector: '화학', basePrice: 6200 },
  { symbol: '002870', name: '신풍제지', engName: 'Sinpoong Paper', market: 'KOSPI', sector: '종이목재', basePrice: 940 },
  { symbol: '002960', name: '한국쉘석유', engName: 'Shell Korea', market: 'KOSPI', sector: '화학', basePrice: 265000 },
  { symbol: '003000', name: '부광약품', engName: 'Bukwang Pharm', market: 'KOSPI', sector: '의약품', basePrice: 6200 },
  { symbol: '003060', name: '에이프로젠바이오로직스', engName: 'Aprogen Biologics', market: 'KOSPI', sector: '의약품', basePrice: 650 },
  { symbol: '007460', name: '에이프로젠', engName: 'Aprogen', market: 'KOSPI', sector: '의약품', basePrice: 1150 },
  { symbol: '003080', name: '성보화학', engName: 'Sungbo Chemical', market: 'KOSPI', sector: '화학', basePrice: 3400 },
  { symbol: '003120', name: '일성건설', engName: 'Ilsung Construction', market: 'KOSPI', sector: '건설업', basePrice: 1680 },
  { symbol: '003200', name: '일지테크', engName: 'Ilji Tech', market: 'KOSPI', sector: '운수장비', basePrice: 3950 },
  { symbol: '003300', name: '한독', engName: 'Handok', market: 'KOSPI', sector: '의약품', basePrice: 13500 },
  { symbol: '003480', name: '한진중공업홀딩스', engName: 'Hanjin Heavy Holdings', market: 'KOSPI', sector: '지주사', basePrice: 3600 },
  { symbol: '097230', name: 'HJ중공업', engName: 'HJ Shipbuilding & Construction', market: 'KOSPI', sector: '건설업', basePrice: 2850 },
  { symbol: '003560', name: 'IHQ', engName: 'IHQ', market: 'KOSPI', sector: '서비스업', basePrice: 850 },
  { symbol: '003570', name: 'SNT다이내믹스', engName: 'SNT Dynamics', market: 'KOSPI', sector: '운수장비', basePrice: 23500 },
  { symbol: '064960', name: 'SNT모티브', engName: 'SNT Motiv', market: 'KOSPI', sector: '운수장비', basePrice: 46000 },
  { symbol: '003580', name: '넥센', engName: 'Nexen', market: 'KOSPI', sector: '지주사', basePrice: 4200 },
  { symbol: '003610', name: '방림', engName: 'Pangrim', market: 'KOSPI', sector: '섬유의복', basePrice: 2150 },
  { symbol: '003690', name: '코리안리', engName: 'Korean Re', market: 'KOSPI', sector: '보험', basePrice: 7800 },
  { symbol: '003830', name: '대한화섬', engName: 'Daehan Synthetic Fiber', market: 'KOSPI', sector: '화학', basePrice: 112000 },
  { symbol: '003960', name: '사조대림', engName: 'Sajo Daerim', market: 'KOSPI', sector: '음식료품', basePrice: 62000 },
  { symbol: '006090', name: '사조오양', engName: 'Sajo Oyang', market: 'KOSPI', sector: '음식료품', basePrice: 8900 },
  { symbol: '007160', name: '사조동아원', engName: 'Sajo DongAOne', market: 'KOSPI', sector: '음식료품', basePrice: 920 },
  { symbol: '008040', name: '사조씨푸드', engName: 'Sajo Seafood', market: 'KOSPI', sector: '음식료품', basePrice: 5100 },
  { symbol: '006040', name: '동원산업', engName: 'Dongwon Industries', market: 'KOSPI', sector: '유통업', basePrice: 38500 },
  { symbol: '014820', name: '동원시스템즈', engName: 'Dongwon Systems', market: 'KOSPI', sector: '철강금속', basePrice: 41000 },
  { symbol: '004080', name: '신흥', engName: 'Shinhung', market: 'KOSPI', sector: '의료정밀', basePrice: 14500 },
  { symbol: '004310', name: '현대약품', engName: 'Hyundai Pharm', market: 'KOSPI', sector: '의약품', basePrice: 4200 },
  { symbol: '004360', name: '세방', engName: 'Sebang', market: 'KOSPI', sector: '운수창고업', basePrice: 11500 },
  { symbol: '004490', name: '세방전지', engName: 'Sebang Global Battery', market: 'KOSPI', sector: '전기전자', basePrice: 84000 },
  { symbol: '004540', name: '깨끗한나라', engName: 'Kleannara', market: 'KOSPI', sector: '종이목재', basePrice: 2450 },
  { symbol: '004560', name: '현대비앤지스틸', engName: 'Hyundai BNG Steel', market: 'KOSPI', sector: '철강금속', basePrice: 16500 },
  { symbol: '004700', name: '조광피혁', engName: 'Chokwang Leather', market: 'KOSPI', sector: '가죽가방신발', basePrice: 46000 },
  { symbol: '004710', name: '한솔테크닉스', engName: 'Hansol Technics', market: 'KOSPI', sector: '전기전자', basePrice: 5600 },
  { symbol: '004720', name: '팜스코', engName: 'Farmsco', market: 'KOSPI', sector: '음식료품', basePrice: 2850 },
  { symbol: '004770', name: '써니전자', engName: 'Sunny Electronics', market: 'KOSPI', sector: '전기전자', basePrice: 1850 },
  { symbol: '004830', name: '덕성', engName: 'Duksung', market: 'KOSPI', sector: '화학', basePrice: 6200 },
  { symbol: '004840', name: 'DRB동일', engName: 'DRB Dongil', market: 'KOSPI', sector: '화학', basePrice: 4600 },
  { symbol: '004870', name: '티웨이홀딩스', engName: 'Tway Holdings', market: 'KOSPI', sector: '지주사', basePrice: 540 },
  { symbol: '091810', name: '티웨이항공', engName: 'Tway Air', market: 'KOSPI', sector: '운수창고업', basePrice: 2850 },
  { symbol: '004890', name: '동일산업', engName: 'Dongil Industries', market: 'KOSPI', sector: '철강금속', basePrice: 42000 },
  { symbol: '004960', name: '한신공영', engName: 'Hanshin E&C', market: 'KOSPI', sector: '건설업', basePrice: 6800 },
  { symbol: '005010', name: '휴스틸', engName: 'Husteel', market: 'KOSPI', sector: '철강금속', basePrice: 4950 },
  { symbol: '005110', name: '한창', engName: 'Hanchang', market: 'KOSPI', sector: '유통업', basePrice: 680 },
  { symbol: '005160', name: '동국홀딩스', engName: 'Dongkuk Holdings', market: 'KOSPI', sector: '지주사', basePrice: 8400 },
  { symbol: '460860', name: '동국씨엠', engName: 'Dongkuk CM', market: 'KOSPI', sector: '철강금속', basePrice: 7200 },
  { symbol: '005250', name: '녹십자홀딩스', engName: 'GC Holdings', market: 'KOSPI', sector: '지주사', basePrice: 14800 },
  { symbol: '005500', name: '삼진제약', engName: 'Samjin Pharm', market: 'KOSPI', sector: '의약품', basePrice: 21500 },
  { symbol: '005690', name: '파미셀', engName: 'Pharmicell', market: 'KOSPI', sector: '의약품', basePrice: 5800 },
  { symbol: '005720', name: '넥센우', engName: 'Nexen (Pref)', market: 'KOSPI', sector: '지주사', basePrice: 3100 },
  { symbol: '005740', name: '크라운해태홀딩스', engName: 'Crown Haitai Holdings', market: 'KOSPI', sector: '지주사', basePrice: 6400 },
  { symbol: '264900', name: '크라운제과', engName: 'Crown Confectionery', market: 'KOSPI', sector: '음식료품', basePrice: 8200 },
  { symbol: '101530', name: '해태제과식품', engName: 'Haitai Confectionery', market: 'KOSPI', sector: '음식료품', basePrice: 5900 },
  { symbol: '005750', name: '대원강업', engName: 'Daewon Kangup', market: 'KOSPI', sector: '철강금속', basePrice: 4200 },
  { symbol: '006060', name: '화승인더', engName: 'Hwaseung Industries', market: 'KOSPI', sector: '화학', basePrice: 3800 },
  { symbol: '241590', name: '화승엔터프라이즈', engName: 'Hwaseung Enterprise', market: 'KOSPI', sector: '가죽가방신발', basePrice: 6800 },
  { symbol: '006110', name: '삼아알미늄', engName: 'Sam-A Aluminium', market: 'KOSPI', sector: '철강금속', basePrice: 84000 },
  { symbol: '006200', name: '한국전자홀딩스', engName: 'KEC Holdings', market: 'KOSPI', sector: '지주사', basePrice: 880 },
  { symbol: '092220', name: 'KEC', engName: 'KEC Corp', market: 'KOSPI', sector: '전기전자', basePrice: 1250 },
  { symbol: '006220', name: '제주은행', engName: 'Jeju Bank', market: 'KOSPI', sector: '금융업', basePrice: 9400 },
  { symbol: '006340', name: '대원전선', engName: 'Daewon Cable', market: 'KOSPI', sector: '전기전자', basePrice: 3450 },
  { symbol: '006370', name: '대구백화점', engName: 'Daegu Department Store', market: 'KOSPI', sector: '유통업', basePrice: 9200 },
  { symbol: '006380', name: '카프로', engName: 'Capro', market: 'KOSPI', sector: '화학', basePrice: 750 },
  { symbol: '006390', name: '현대건설우', engName: 'Hyundai E&C (Pref)', market: 'KOSPI', sector: '건설업', basePrice: 78000 },
  { symbol: '006650', name: '대한유화', engName: 'Korea Petrochemical', market: 'KOSPI', sector: '화학', basePrice: 98000 },
  { symbol: '006740', name: '영풍', engName: 'Young Poong', market: 'KOSPI', sector: '철강금속', basePrice: 395000 },
  { symbol: '006840', name: 'AK홀딩스', engName: 'AK Holdings', market: 'KOSPI', sector: '지주사', basePrice: 12800 },
  { symbol: '089590', name: '제주항공', engName: 'Jeju Air', market: 'KOSPI', sector: '운수창고업', basePrice: 9800 },
  { symbol: '006880', name: '신송홀딩스', engName: 'Sinsong Holdings', market: 'KOSPI', sector: '지주사', basePrice: 7200 },
  { symbol: '007110', name: '일신석재', engName: 'Ilshin Stone', market: 'KOSPI', sector: '비금속광물', basePrice: 1280 },
  { symbol: '007120', name: '미래아이앤지', engName: 'Mirae ING', market: 'KOSPI', sector: '서비스업', basePrice: 210 },
  { symbol: '007210', name: '벽산', engName: 'Byucksan', market: 'KOSPI', sector: '비금속광물', basePrice: 2450 },
  { symbol: '007280', name: '한국특강', engName: 'Korea Steel Shapes', market: 'KOSPI', sector: '철강금속', basePrice: 2150 },
  { symbol: '007340', name: '디엔에프', engName: 'DNF', market: 'KOSPI', sector: '화학', basePrice: 18500 },
  { symbol: '007390', name: '네이처셀', engName: 'Nature Cell', market: 'KOSPI', sector: '음식료품', basePrice: 14500 },
  { symbol: '007540', name: '샘표', engName: 'Sempio', market: 'KOSPI', sector: '지주사', basePrice: 46000 },
  { symbol: '248170', name: '샘표식품', engName: 'Sempio Foods', market: 'KOSPI', sector: '음식료품', basePrice: 29500 },
  { symbol: '007570', name: '일양약품', engName: 'Ilyang Pharm', market: 'KOSPI', sector: '의약품', basePrice: 14800 },
  { symbol: '007610', name: '선진', engName: 'Sunjin', market: 'KOSPI', sector: '음식료품', basePrice: 7200 },
  { symbol: '007690', name: '국도화학', engName: 'Kukdo Chemical', market: 'KOSPI', sector: '화학', basePrice: 38000 },
  { symbol: '007700', name: 'F&F홀딩스', engName: 'F&F Holdings', market: 'KOSPI', sector: '지주사', basePrice: 14200 },
  { symbol: '383220', name: 'F&F', engName: 'F&F', market: 'KOSPI', sector: '섬유의복', basePrice: 62000 },
  { symbol: '007810', name: '코리아써키트', engName: 'Korea Circuit', market: 'KOSPI', sector: '전기전자', basePrice: 14800 },
  { symbol: '008060', name: '대덕', engName: 'Daeduck', market: 'KOSPI', sector: '지주사', basePrice: 6200 },
  { symbol: '353200', name: '대덕전자', engName: 'Daeduck Electronics', market: 'KOSPI', sector: '전기전자', basePrice: 21500 },
  { symbol: '008250', name: '이건산업', engName: 'Eagon Industrial', market: 'KOSPI', sector: '종이목재', basePrice: 5800 },
  { symbol: '008260', name: 'NI스틸', engName: 'NI Steel', market: 'KOSPI', sector: '철강금속', basePrice: 4600 },
  { symbol: '008350', name: '남선알미늄', engName: 'Namsun Aluminium', market: 'KOSPI', sector: '철강금속', basePrice: 1850 },
  { symbol: '008420', name: '문배철강', engName: 'Moonbae Steel', market: 'KOSPI', sector: '철강금속', basePrice: 2950 },
  { symbol: '008490', name: '서원', engName: 'Seowon', market: 'KOSPI', sector: '철강금속', basePrice: 1350 },
  { symbol: '008500', name: '일정실업', engName: 'Iljeong Industrial', market: 'KOSPI', sector: '섬유의복', basePrice: 16500 },
  { symbol: '008700', name: '아남전자', engName: 'Anam Electronics', market: 'KOSPI', sector: '전기전자', basePrice: 1720 },
  { symbol: '008730', name: '율촌화학', engName: 'Youlchon Chemical', market: 'KOSPI', sector: '화학', basePrice: 28500 },
  { symbol: '008930', name: '한미사이언스', engName: 'Hanmi Science', market: 'KOSPI', sector: '지주사', basePrice: 34500 },
  { symbol: '008970', name: '동양철관', engName: 'Dongyang Steel Pipe', market: 'KOSPI', sector: '철강금속', basePrice: 940 },
  { symbol: '009070', name: 'KCTC', engName: 'KCTC', market: 'KOSPI', sector: '운수창고업', basePrice: 4600 },
  { symbol: '009140', name: '경인전자', engName: 'Kyungin Electronics', market: 'KOSPI', sector: '전기전자', basePrice: 22500 },
  { symbol: '009160', name: 'SIMPAC', engName: 'SIMPAC', market: 'KOSPI', sector: '철강금속', basePrice: 4200 },
  { symbol: '009180', name: '한솔로지스틱스', engName: 'Hansol Logistics', market: 'KOSPI', sector: '운수창고업', basePrice: 2450 },
  { symbol: '009190', name: '대양금속', engName: 'Dae Yang Metal', market: 'KOSPI', sector: '철강금속', basePrice: 1650 },
  { symbol: '009200', name: '무림페이퍼', engName: 'Moorim Paper', market: 'KOSPI', sector: '종이목재', basePrice: 2150 },
  { symbol: '009580', name: '무림P&P', engName: 'Moorim P&P', market: 'KOSPI', sector: '종이목재', basePrice: 3250 },
  { symbol: '004150', name: '한솔제지', engName: 'Hansol Paper', market: 'KOSPI', sector: '종이목재', basePrice: 9800 },
  { symbol: '009320', name: '대우부품', engName: 'Daewoo Electronic Components', market: 'KOSPI', sector: '전기전자', basePrice: 1250 },
  { symbol: '009410', name: '태영건설', engName: 'Taeyoung E&C', market: 'KOSPI', sector: '건설업', basePrice: 2450 },
  { symbol: '009420', name: '한올바이오파마', engName: 'HanAll Biopharma', market: 'KOSPI', sector: '의약품', basePrice: 38500 },
  { symbol: '009440', name: 'KC그린홀딩스', engName: 'KC Green Holdings', market: 'KOSPI', sector: '지주사', basePrice: 1150 },
  { symbol: '119650', name: 'KC코트렐', engName: 'KC Cottrell', market: 'KOSPI', sector: '기계', basePrice: 780 },
  { symbol: '009450', name: '경동나비엔', engName: 'KyungDong Navien', market: 'KOSPI', sector: '기계', basePrice: 84000 },
  { symbol: '009470', name: '삼화전기', engName: 'Samwha Electric', market: 'KOSPI', sector: '전기전자', basePrice: 58000 },
  { symbol: '009770', name: '삼화콘덴서', engName: 'Samwha Capacitor', market: 'KOSPI', sector: '전기전자', basePrice: 36000 },
  { symbol: '009830', name: '한화솔루션', engName: 'Hanwha Solutions', market: 'KOSPI', sector: '화학', basePrice: 22000 },
  { symbol: '088350', name: '한화생명', engName: 'Hanwha Life Insurance', market: 'KOSPI', sector: '보험', basePrice: 3100 },
  { symbol: '000370', name: '한화손해보험', engName: 'Hanwha General Insurance', market: 'KOSPI', sector: '보험', basePrice: 4800 },
  { symbol: '000880', name: '한화', engName: 'Hanwha Corp', market: 'KOSPI', sector: '지주사', basePrice: 28500 },
  { symbol: '272210', name: '한화시스템', engName: 'Hanwha Systems', market: 'KOSPI', sector: '전기전자', basePrice: 21500 },
  { symbol: '077970', name: 'STX엔진', engName: 'STX Engine', market: 'KOSPI', sector: '운수장비', basePrice: 18500 },
  { symbol: '011810', name: 'STX', engName: 'STX Corp', market: 'KOSPI', sector: '유통업', basePrice: 8900 },
  { symbol: '443060', name: 'STX그린로지스', engName: 'STX Green Logis', market: 'KOSPI', sector: '운수창고업', basePrice: 8200 },
  { symbol: '083650', name: '비에이치아이', engName: 'BHI', market: 'KOSPI', sector: '기계', basePrice: 12500 },
  { symbol: '090350', name: '노루페인트', engName: 'Noro Paint', market: 'KOSPI', sector: '화학', basePrice: 8400 },
  { symbol: '003160', name: '디아이', engName: 'DI Corp', market: 'KOSPI', sector: '전기전자', basePrice: 21500 },
  { symbol: '014830', name: '유니드', engName: 'Unid', market: 'KOSPI', sector: '화학', basePrice: 72000 },
  { symbol: '448420', name: '유니드비티플러스', engName: 'Unid BT Plus', market: 'KOSPI', sector: '종이목재', basePrice: 6800 },
  { symbol: '010060', name: 'OCI홀딩스', engName: 'OCI Holdings', market: 'KOSPI', sector: '지주사', basePrice: 82000 },
  { symbol: '456040', name: 'OCI', engName: 'OCI Company', market: 'KOSPI', sector: '화학', basePrice: 84000 },
  { symbol: '016710', name: '대성홀딩스', engName: 'Daesung Holdings', market: 'KOSPI', sector: '지주사', basePrice: 9800 },
  { symbol: '117580', name: '대성에너지', engName: 'Daesung Energy', market: 'KOSPI', sector: '전기가스업', basePrice: 8400 },
  { symbol: '005950', name: '이수화학', engName: 'ISU Chemical', market: 'KOSPI', sector: '화학', basePrice: 9400 },
  { symbol: '457190', name: '이수스페셜티케미컬', engName: 'ISU Specialty Chemical', market: 'KOSPI', sector: '화학', basePrice: 48500 },
  { symbol: '004000', name: '롯데정밀화학', engName: 'Lotte Fine Chemical', market: 'KOSPI', sector: '화학', basePrice: 48500 },
  { symbol: '001250', name: 'GS글로벌', engName: 'GS Global', market: 'KOSPI', sector: '유통업', basePrice: 3100 },
  { symbol: '007590', name: '동화약품', engName: 'Dongwha Pharm', market: 'KOSPI', sector: '의약품', basePrice: 9400 },
  { symbol: '002410', name: '범양건영', engName: 'Bumyang Construction', market: 'KOSPI', sector: '건설업', basePrice: 1850 },
  { symbol: '013580', name: '계룡건설', engName: 'Kyeryong Construction', market: 'KOSPI', sector: '건설업', basePrice: 12400 },
  { symbol: '013700', name: '까뮤이앤씨', engName: 'Cammsys E&C', market: 'KOSPI', sector: '건설업', basePrice: 1100 },
  { symbol: '001210', name: '금호전기', engName: 'Kumho Electric', market: 'KOSPI', sector: '전기전자', basePrice: 720 },
  { symbol: '010580', name: '에스엠벡셀', engName: 'SM BEXEL', market: 'KOSPI', sector: '전기전자', basePrice: 2450 },
  { symbol: '017940', name: 'E1', engName: 'E1 Corp', market: 'KOSPI', sector: '유통업', basePrice: 74000 },
  { symbol: '001460', name: 'BYC', engName: 'BYC', market: 'KOSPI', sector: '섬유의복', basePrice: 460000 },
  { symbol: '001470', name: '삼부토건', engName: 'Sambu Construction', market: 'KOSPI', sector: '건설업', basePrice: 1150 },
  { symbol: '001620', name: '케이비아이동국실업', engName: 'KBI Dongkuk Ind', market: 'KOSPI', sector: '운수장비', basePrice: 780 },
  { symbol: '001720', name: '신영와코루', engName: 'Shinyoung Wacoal', market: 'KOSPI', sector: '섬유의복', basePrice: 9800 },
  { symbol: '002240', name: '고려제강', engName: 'Kiswire', market: 'KOSPI', sector: '철강금속', basePrice: 22000 },
  { symbol: '002390', name: '한독크린텍', engName: 'Handok Clean Tech', market: 'KOSPI', sector: '제조업', basePrice: 6500 },
  { symbol: '003220', name: '대원제약', engName: 'Daewon Pharm', market: 'KOSPI', sector: '의약품', basePrice: 15400 },
  { symbol: '003350', name: '한국화장품제조', engName: 'Hankook Cosmetics Mfg', market: 'KOSPI', sector: '화학', basePrice: 58000 },
  { symbol: '123690', name: '한국화장품', engName: 'Hankook Cosmetics', market: 'KOSPI', sector: '유통업', basePrice: 7800 },
  { symbol: '003780', name: '진양산업', engName: 'Chinyang Industry', market: 'KOSPI', sector: '화학', basePrice: 6800 },
  { symbol: '010040', name: '한국내화', engName: 'Korea Refractories', market: 'KOSPI', sector: '비금속광물', basePrice: 2950 },
  { symbol: '014280', name: '금강공업', engName: 'Kumkang Kind', market: 'KOSPI', sector: '철강금속', basePrice: 5400 },
  { symbol: '015350', name: '유성기업', engName: 'Yusung Enterprise', market: 'KOSPI', sector: '운수장비', basePrice: 2600 },
  { symbol: '016580', name: '환인제약', engName: 'Whanin Pharm', market: 'KOSPI', sector: '의약품', basePrice: 14200 },
  { symbol: '016590', name: '신대양제지', engName: 'Shindaeyang Paper', market: 'KOSPI', sector: '종이목재', basePrice: 6200 },
  { symbol: '016800', name: '퍼시스', engName: 'Fursys', market: 'KOSPI', sector: '가구', basePrice: 38500 },
  { symbol: '017800', name: '현대엘리베이터', engName: 'Hyundai Elevator', market: 'KOSPI', sector: '기계', basePrice: 46000 },
  { symbol: '017810', name: '풀무원', engName: 'Pulmuone', market: 'KOSPI', sector: '음식료품', basePrice: 12500 },
  { symbol: '017900', name: '광전자', engName: 'AUK Corp', market: 'KOSPI', sector: '전기전자', basePrice: 2150 },
  { symbol: '020150', name: '일진타이거', engName: 'Iljin', market: 'KOSPI', sector: '기계', basePrice: 18500 },
  { symbol: '020760', name: '일진디스플', engName: 'Iljin Display', market: 'KOSPI', sector: '전기전자', basePrice: 1050 },
  { symbol: '023810', name: '인팩', engName: 'Infac', market: 'KOSPI', sector: '운수장비', basePrice: 7800 },
  { symbol: '024070', name: 'WISCOM', engName: 'Wiscom', market: 'KOSPI', sector: '화학', basePrice: 2650 },
  { symbol: '025320', name: '시노펙스', engName: 'Synopex', market: 'KOSPI', sector: '전기전자', basePrice: 8400 },
  { symbol: '027740', name: '마니커', engName: 'Maniker', market: 'KOSPI', sector: '음식료품', basePrice: 1100 },
  { symbol: '030000', name: '제일기획', engName: 'Cheil Worldwide', market: 'KOSPI', sector: '서비스업', basePrice: 18500 },
  { symbol: '030610', name: '교보증권', engName: 'Kyobo Securities', market: 'KOSPI', sector: '증권', basePrice: 5600 },
  { symbol: '030720', name: '동원수산', engName: 'Dongwon Fisheries', market: 'KOSPI', sector: '음식료품', basePrice: 7800 },
  { symbol: '031430', name: '신세계인터내셔날', engName: 'Shinsegae International', market: 'KOSPI', sector: '유통업', basePrice: 13500 },
  { symbol: '031440', name: '신세계푸드', engName: 'Shinsegae Food', market: 'KOSPI', sector: '음식료품', basePrice: 38500 },
  { symbol: '033180', name: '필룩스(KH 필룩스)', engName: 'KH Feelux', market: 'KOSPI', sector: '전기전자', basePrice: 520 },
  { symbol: '033240', name: '자화전자', engName: 'Jahwa Electronics', market: 'KOSPI', sector: '전기전자', basePrice: 21500 },
  { symbol: '033270', name: '유나이티드제약', engName: 'Korea United Pharm', market: 'KOSPI', sector: '의약품', basePrice: 24500 },
  { symbol: '033920', name: '무학', engName: 'Muhak', market: 'KOSPI', sector: '음식료품', basePrice: 5400 },
  { symbol: '034120', name: 'SBS', engName: 'SBS', market: 'KOSPI', sector: '서비스업', basePrice: 22000 },
  { symbol: '034300', name: '신세계건설', engName: 'Shinsegae E&C', market: 'KOSPI', sector: '건설업', basePrice: 16500 },
  { symbol: '034590', name: '인천도시가스', engName: 'Incheon City Gas', market: 'KOSPI', sector: '전기가스업', basePrice: 26500 },
  { symbol: '034810', name: '해성산업', engName: 'Haesung Industrial', market: 'KOSPI', sector: '지주사', basePrice: 7800 },
  { symbol: '035150', name: '백산', engName: 'Baeksan', market: 'KOSPI', sector: '가죽가방신발', basePrice: 12500 },
  { symbol: '036490', name: '대동전자', engName: 'Daedong Electronics', market: 'KOSPI', sector: '전기전자', basePrice: 7800 },
  { symbol: '037270', name: 'YG PLUS', engName: 'YG PLUS', market: 'KOSPI', sector: '서비스업', basePrice: 4200 },
  { symbol: '037560', name: 'LG헬로비전', engName: 'LG HelloVision', market: 'KOSPI', sector: '통신업', basePrice: 2850 },
  { symbol: '038540', name: '상상인증권', engName: 'Sangsangin Securities', market: 'KOSPI', sector: '증권', basePrice: 740 },
  { symbol: '042670', name: 'HD현대인프라코어', engName: 'HD Hyundai Infracore', market: 'KOSPI', sector: '기계', basePrice: 7900 },
  { symbol: '071840', name: '롯데하이마트', engName: 'Lotte Hi-Mart', market: 'KOSPI', sector: '유통업', basePrice: 8900 },
  { symbol: '072710', name: '농심홀딩스', engName: 'Nongshim Holdings', market: 'KOSPI', sector: '지주사', basePrice: 68000 },
  { symbol: '073240', name: '금호타이어', engName: 'Kumho Tire', market: 'KOSPI', sector: '화학', basePrice: 5400 },
  { symbol: '079980', name: '휴비스', engName: 'Huvis', market: 'KOSPI', sector: '화학', basePrice: 3850 },
  { symbol: '081660', name: '휠라홀딩스', engName: 'Fila Holdings', market: 'KOSPI', sector: '유통업', basePrice: 39500 },
  { symbol: '084870', name: '베트남개발1', engName: 'Vietnam Development 1', market: 'KOSPI', sector: '금융업', basePrice: 240 },
  { symbol: '086280', name: '현대글로비스', engName: 'Hyundai Glovis', market: 'KOSPI', sector: '운수창고업', basePrice: 118000 },
  { symbol: '088980', name: '맥쿼리인프라', engName: 'Macquarie Korea Infra', market: 'KOSPI', sector: '금융업', basePrice: 11800 },
  { symbol: '092200', name: '디아이씨', engName: 'DIC Corp', market: 'KOSPI', sector: '운수장비', basePrice: 4100 },
  { symbol: '093050', name: 'LF', engName: 'LF Corp', market: 'KOSPI', sector: '유통업', basePrice: 14800 },
  { symbol: '093370', name: '후성', engName: 'Foosung', market: 'KOSPI', sector: '화학', basePrice: 6800 },
  { symbol: '095570', name: 'AJ네트웍스', engName: 'AJ Networks', market: 'KOSPI', sector: '서비스업', basePrice: 4600 },
  { symbol: '097520', name: '엠씨넥스', engName: 'MCNEX', market: 'KOSPI', sector: '전기전자', basePrice: 26500 },
  { symbol: '100840', name: 'SNT에너지', engName: 'SNT Energy', market: 'KOSPI', sector: '기계', basePrice: 22000 },
  { symbol: '107590', name: '미원홀딩스', engName: 'Miwon Holdings', market: 'KOSPI', sector: '지주사', basePrice: 84000 },
  { symbol: '111770', name: '영원무역', engName: 'Youngone Corp', market: 'KOSPI', sector: '섬유의복', basePrice: 42000 },
  { symbol: '114090', name: 'GKL', engName: 'Grand Korea Leisure', market: 'KOSPI', sector: '서비스업', basePrice: 11800 },
  { symbol: '115390', name: '락앤락', engName: 'Lock&Lock', market: 'KOSPI', sector: '화학', basePrice: 8700 },
  { symbol: '138930', name: 'BNK금융지주', engName: 'BNK Financial Group', market: 'KOSPI', sector: '금융업', basePrice: 9400 },
  { symbol: '175330', name: 'JB금융지주', engName: 'JB Financial Group', market: 'KOSPI', sector: '금융업', basePrice: 15800 },
  { symbol: '192080', name: '더블유게임즈', engName: 'DoubleUGames', market: 'KOSPI', sector: '서비스업', basePrice: 48000 },
  { symbol: '200880', name: '서연이화', engName: 'Seoyon E-Hwa', market: 'KOSPI', sector: '운수장비', basePrice: 16500 },
  { symbol: '204210', name: '모두투어', engName: 'Modetour', market: 'KOSPI', sector: '서비스업', basePrice: 12500 },
  { symbol: '241560', name: '두산밥캣', engName: 'Doosan Bobcat', market: 'KOSPI', sector: '기계', basePrice: 42000 },
  { symbol: '271980', name: '제일약품', engName: 'Jeil Pharm', market: 'KOSPI', sector: '의약품', basePrice: 13500 },
  { symbol: '284740', name: '쿠쿠홈시스', engName: 'Cuckoo Homesys', market: 'KOSPI', sector: '유통업', basePrice: 21500 },
  { symbol: '192400', name: '쿠쿠홀딩스', engName: 'Cuckoo Holdings', market: 'KOSPI', sector: '지주사', basePrice: 19800 },
  { symbol: '302440', name: 'SK바이오사이언스', engName: 'SK Bioscience', market: 'KOSPI', sector: '의약품', basePrice: 52000 },
  { symbol: '326030', name: 'SK바이오팜', engName: 'SK Biopharmaceuticals', market: 'KOSPI', sector: '의약품', basePrice: 108000 },
  { symbol: '330590', name: '롯데렌탈', engName: 'Lotte Rental', market: 'KOSPI', sector: '서비스업', basePrice: 28500 },
  { symbol: '336260', name: '두산퓨얼셀', engName: 'Doosan Fuel Cell', market: 'KOSPI', sector: '전기전자', basePrice: 19800 },
  { symbol: '361610', name: 'SK아이이테크놀로지', engName: 'SK IE Technology', market: 'KOSPI', sector: '전기전자', basePrice: 38500 },
  { symbol: '377300', name: '카카오페이', engName: 'Kakao Pay', market: 'KOSPI', sector: '서비스업', basePrice: 26500 },
  { symbol: '402340', name: 'SK스퀘어', engName: 'SK Square', market: 'KOSPI', sector: '지주사', basePrice: 84000 },
  { symbol: '454910', name: '두산로보틱스', engName: 'Doosan Robotics', market: 'KOSPI', sector: '기계', basePrice: 68000 },
  { symbol: '443060', name: 'HD현대마린솔루션', engName: 'HD Hyundai Marine Solution', market: 'KOSPI', sector: '서비스업', basePrice: 135000 },
  { symbol: '278470', name: '에이피알', engName: 'APR', market: 'KOSPI', sector: '화학', basePrice: 265000 },
  { symbol: '069500', name: 'KODEX 200', engName: 'KODEX 200 ETF', market: 'KOSPI', sector: 'ETF', basePrice: 36500 },
  { symbol: '122630', name: 'KODEX 레버리지', engName: 'KODEX Leverage ETF', market: 'KOSPI', sector: 'ETF', basePrice: 16500 },
  { symbol: '114800', name: 'KODEX 인버스', engName: 'KODEX Inverse ETF', market: 'KOSPI', sector: 'ETF', basePrice: 4200 },
  { symbol: '252670', name: 'KODEX 200선물인버스2X', engName: 'KODEX 200 Inverse 2X', market: 'KOSPI', sector: 'ETF', basePrice: 2150 },
  { symbol: '371460', name: 'TIGER 차이나전기차SOLACTIVE', engName: 'TIGER China EV', market: 'KOSPI', sector: 'ETF', basePrice: 8900 },
  { symbol: '133690', name: 'TIGER 미국나스닥100', engName: 'TIGER US Nasdaq 100', market: 'KOSPI', sector: 'ETF', basePrice: 112000 },
  { symbol: '360750', name: 'TIGER 미국S&P500', engName: 'TIGER US S&P 500', market: 'KOSPI', sector: 'ETF', basePrice: 18500 }
];

// 초성 인덱스 자동 초기화
KOSPI_STOCKS.forEach(stock => {
  stock.initials = getChosung(stock.name);
});

// 코스닥(KOSDAQ) 대표 활성 종목 (검색시 2순위로 밀림)
export const KOSDAQ_STOCKS: MasterStock[] = [
  { symbol: '247540', name: '에코프로비엠', engName: 'Ecopro BM', market: 'KOSDAQ', sector: '일반전기전자', basePrice: 172000 },
  { symbol: '086520', name: '에코프로', engName: 'Ecopro', market: 'KOSDAQ', sector: '금융', basePrice: 84000 },
  { symbol: '196170', name: '알테오젠', engName: 'Alteogen', market: 'KOSDAQ', sector: '기타서비스', basePrice: 382000 },
  { symbol: '028300', name: 'HLB', engName: 'HLB', market: 'KOSDAQ', sector: '운송장비부품', basePrice: 88500 },
  { symbol: '141080', name: '리가켐바이오', engName: 'LigaChem Biosciences', market: 'KOSDAQ', sector: '기타서비스', basePrice: 114000 },
  { symbol: '277810', name: '레인보우로보틱스', engName: 'Rainbow Robotics', market: 'KOSDAQ', sector: '기계장비', basePrice: 148000 },
  { symbol: '348370', name: '엔켐', engName: 'Enchem', market: 'KOSDAQ', sector: '화학', basePrice: 182000 },
  { symbol: '263750', name: '펄어비스', engName: 'Pearl Abyss', market: 'KOSDAQ', sector: '디지털컨텐츠', basePrice: 36000 },
  { symbol: '293490', name: '카카오게임즈', engName: 'Kakao Games', market: 'KOSDAQ', sector: '디지털컨텐츠', basePrice: 18500 },
  { symbol: '035900', name: 'JYP Ent.', engName: 'JYP Entertainment', market: 'KOSDAQ', sector: '엔터테인먼트', basePrice: 56000 },
  { symbol: '041510', name: '에스엠', engName: 'SM Entertainment', market: 'KOSDAQ', sector: '엔터테인먼트', basePrice: 72000 },
  { symbol: '122870', name: '와이지엔터테인먼트', engName: 'YG Entertainment', market: 'KOSDAQ', sector: '엔터테인먼트', basePrice: 39500 },
  { symbol: '058470', name: '리노공업', engName: 'LEENO Industrial', market: 'KOSDAQ', sector: '반도체', basePrice: 205000 },
  { symbol: '039030', name: '이오테크닉스', engName: 'EO Technics', market: 'KOSDAQ', sector: '반도체', basePrice: 175000 },
  { symbol: '240810', name: '원익IPS', engName: 'Wonik IPS', market: 'KOSDAQ', sector: '반도체', basePrice: 32000 },
  { symbol: '095610', name: '테스', engName: 'TES', market: 'KOSDAQ', sector: '반도체', basePrice: 28500 },
  { symbol: '036540', name: 'SFA반도체', engName: 'SFA Semiconductor', market: 'KOSDAQ', sector: '반도체', basePrice: 5200 },
  { symbol: '067310', name: '하나마이크론', engName: 'Hana Micron', market: 'KOSDAQ', sector: '반도체', basePrice: 18500 },
  { symbol: '036490', name: 'HPSP', engName: 'HPSP', market: 'KOSDAQ', sector: '반도체', basePrice: 38000 },
  { symbol: '233740', name: 'KODEX 코스닥150레버리지', engName: 'KODEX Kosdaq 150 Lev', market: 'KOSDAQ', sector: 'ETF', basePrice: 8400 },
  { symbol: '251340', name: 'KODEX 코스닥150선물인버스', engName: 'KODEX Kosdaq 150 Inv', market: 'KOSDAQ', sector: 'ETF', basePrice: 3900 }
];

KOSDAQ_STOCKS.forEach(stock => {
  stock.initials = getChosung(stock.name);
});

// 코스피 우선 통합 리스트
export const ALL_KRX_MASTER_STOCKS: MasterStock[] = [
  ...KOSPI_STOCKS,
  ...KOSDAQ_STOCKS
];

// 코스피 1순위 최우선 검색 알고리즘
export function searchKrMasterStocks(query: string, maxResults = 30): MasterStock[] {
  if (!query || !query.trim()) return [];

  const rawQuery = query.trim();
  const lowerQuery = rawQuery.toLowerCase();
  const isChosungQuery = /^[ㄱ-ㅎ]+$/.test(rawQuery);
  const isNumericCode = /^\d{1,6}$/.test(rawQuery);

  const matched: Array<{ stock: MasterStock; score: number }> = [];

  for (const stock of ALL_KRX_MASTER_STOCKS) {
    let score = 0;
    const nameLower = stock.name.toLowerCase();
    const sym = stock.symbol;
    const engLower = (stock.engName || '').toLowerCase();
    const initials = stock.initials || '';

    // 코스피(KOSPI) 종목 가산점 (+5000점) -> 코스피가 무조건 코스닥보다 1순위 상단에 노출
    const kospiBonus = stock.market === 'KOSPI' ? 5000 : 0;

    if (sym === rawQuery) {
      score = 10000 + kospiBonus; // 종목코드 완벽 일치
    } else if (nameLower === lowerQuery) {
      score = 9000 + kospiBonus; // 종목명 완벽 일치
    } else if (sym.startsWith(rawQuery)) {
      score = 8000 + kospiBonus + (100 - sym.length); // 종목코드 접두사 일치
    } else if (nameLower.startsWith(lowerQuery)) {
      score = 7000 + kospiBonus + (100 - nameLower.length); // 종목명 접두사 일치
    } else if (nameLower.includes(lowerQuery)) {
      score = 6000 + kospiBonus; // 종목명 포함
    } else if (isChosungQuery && initials.includes(rawQuery)) {
      score = 5000 + kospiBonus + (initials.startsWith(rawQuery) ? 500 : 0); // 초성 일치 (예: 'ㅅㅅㅈㅈ' -> 삼성전자)
    } else if (engLower.includes(lowerQuery)) {
      score = 4000 + kospiBonus; // 영문명 포함
    } else if (isNumericCode && sym.includes(rawQuery)) {
      score = 3000 + kospiBonus; // 숫자 코드 포함
    }

    if (score > 0) {
      matched.push({ stock, score });
    }
  }

  // 높은 점수 순(KOSPI 최우선)으로 정렬
  matched.sort((a, b) => b.score - a.score);

  return matched.slice(0, maxResults).map(m => m.stock);
}
