export interface StockSuggestion {
  symbol: string;
  name: string;
  market: 'KR' | 'US';
  price?: number;
}

export const POPULAR_STOCKS: StockSuggestion[] = [
  // KR Stocks (Domestic with both Korean and English Names/Codes)
  { symbol: '005930', name: '삼성전자 (Samsung Electronics)', market: 'KR' },
  { symbol: '000660', name: 'SK하이닉스 (SK hynix)', market: 'KR' },
  { symbol: '373220', name: 'LG에너지솔루션 (LG Energy Solution)', market: 'KR' },
  { symbol: '207940', name: '삼성바이오로직스 (Samsung Biologics)', market: 'KR' },
  { symbol: '005380', name: '현대차 (Hyundai Motor)', market: 'KR' },
  { symbol: '035420', name: 'NAVER (네이버)', market: 'KR' },
  { symbol: '035720', name: '카카오 (Kakao)', market: 'KR' },
  { symbol: '000270', name: '기아 (Kia)', market: 'KR' },
  { symbol: '068270', name: '셀트리온 (Celltrion)', market: 'KR' },
  { symbol: '005490', name: 'POSCO홀딩스 (POSCO Holdings)', market: 'KR' },
  { symbol: '105560', name: 'KB금융 (KB Financial)', market: 'KR' },
  { symbol: '055550', name: '신한지주 (Shinhan Financial)', market: 'KR' },
  { symbol: '006400', name: '삼성SDI (Samsung SDI)', market: 'KR' },
  { symbol: '051910', name: 'LG화학 (LG Chem)', market: 'KR' },
  { symbol: '012330', name: '현대모비스 (Hyundai Mobis)', market: 'KR' },
  { symbol: '028260', name: '삼성물산 (Samsung C&T)', market: 'KR' },
  { symbol: '086790', name: '하나금융지주 (Hana Financial)', market: 'KR' },
  { symbol: '138040', name: '메리츠금융지주 (Meritz Financial)', market: 'KR' },
  { symbol: '034730', name: 'SK (에스케이)', market: 'KR' },
  { symbol: '003550', name: 'LG (엘지)', market: 'KR' },
  { symbol: '247540', name: '에코프로비엠 (Ecopro BM)', market: 'KR' },
  { symbol: '086520', name: '에코프로 (Ecopro)', market: 'KR' },
  { symbol: '196170', name: '알테오젠 (Alteogen)', market: 'KR' },
  { symbol: '028300', name: 'HLB (에이치엘비)', market: 'KR' },
  { symbol: '042700', name: '한미반도체 (Hanmi Semiconductor)', market: 'KR' },
  { symbol: '012450', name: '한화에어로스페이스 (Hanwha Aerospace)', market: 'KR' },
  { symbol: '079550', name: 'LIG넥스원 (LIG Nex1)', market: 'KR' },
  { symbol: '025820', name: '이구산업 (Lee Ku Industrial)', market: 'KR' },
  { symbol: '001520', name: '동양 (Tongyang)', market: 'KR' },
  { symbol: '025560', name: '미래산업 (Mirae Corp)', market: 'KR' },
  { symbol: '004060', name: 'SG세계물산 (SG Global)', market: 'KR' },
  { symbol: '014160', name: '대영포장 (Daeyoung Packaging)', market: 'KR' },
  { symbol: '073240', name: '금호타이어 (Kumho Tire)', market: 'KR' },
  { symbol: '030200', name: 'KT (케이티)', market: 'KR' },
  { symbol: '017670', name: 'SK텔레콤 (SK Telecom)', market: 'KR' },
  { symbol: '032830', name: '삼성생명 (Samsung Life)', market: 'KR' },
  { symbol: '018260', name: '삼성에스디에스 (Samsung SDS)', market: 'KR' },
  { symbol: '010140', name: '삼성중공업 (Samsung Heavy)', market: 'KR' },
  { symbol: '009540', name: 'HD한국조선해양 (HD Korea Shipbuilding)', market: 'KR' },
  { symbol: '329180', name: 'HD현대중공업 (HD Hyundai Heavy)', market: 'KR' },
  { symbol: '010950', name: 'S-Oil (에쓰오일)', market: 'KR' },
  { symbol: '036570', name: '엔씨소프트 (NCSOFT)', market: 'KR' },
  { symbol: '251270', name: '넷마블 (Netmarble)', market: 'KR' },
  { symbol: '263750', name: '펄어비스 (Pearl Abyss)', market: 'KR' },
  { symbol: '293490', name: '카카오게임즈 (Kakao Games)', market: 'KR' },
  { symbol: '352820', name: '하이브 (HYBE)', market: 'KR' },
  { symbol: '069500', name: 'KODEX 200 (코덱스 200)', market: 'KR' },
  { symbol: '122630', name: 'KODEX 레버리지 (KODEX Leverage)', market: 'KR' },
  { symbol: '133690', name: 'TIGER 미국나스닥100 (TIGER US Nasdaq 100)', market: 'KR' },
  { symbol: '360750', name: 'TIGER 미국S&P500 (TIGER US S&P 500)', market: 'KR' },
  
  // US Stocks (Major US Stocks with English and Korean Names/Codes)
  { symbol: 'NVDA', name: '엔비디아 (NVIDIA Corp)', market: 'US' },
  { symbol: 'AAPL', name: '애플 (Apple Inc)', market: 'US' },
  { symbol: 'TSLA', name: '테슬라 (Tesla Inc)', market: 'US' },
  { symbol: 'MSFT', name: '마이크로소프트 (Microsoft Corp)', market: 'US' },
  { symbol: 'GOOGL', name: '알파벳 A / 구글 (Alphabet Google A)', market: 'US' },
  { symbol: 'GOOG', name: '알파벳 C / 구글 (Alphabet Google C)', market: 'US' },
  { symbol: 'AMZN', name: '아마존 (Amazon.com Inc)', market: 'US' },
  { symbol: 'META', name: '메타 / 페이스북 (Meta Platforms)', market: 'US' },
  { symbol: 'AMD', name: 'AMD (어드밴스드 마이크로 디바이스)', market: 'US' },
  { symbol: 'PLTR', name: '팔란티어 (Palantir Technologies)', market: 'US' },
  { symbol: 'NFLX', name: '넷플릭스 (Netflix Inc)', market: 'US' },
  { symbol: 'AVGO', name: '브로드컴 (Broadcom Inc)', market: 'US' },
  { symbol: 'ARM', name: 'ARM 홀딩스 (Arm Holdings)', market: 'US' },
  { symbol: 'SMCI', name: '슈퍼마이크로 (Super Micro Computer)', market: 'US' },
  { symbol: 'COIN', name: '코인베이스 (Coinbase Global)', market: 'US' },
  { symbol: 'MARA', name: '마라톤 디지털 (MARA Holdings)', market: 'US' },
  { symbol: 'RIOT', name: '라이엇 플랫폼스 (Riot Platforms)', market: 'US' },
  { symbol: 'SOUN', name: '사운드하운드 AI (SoundHound AI)', market: 'US' },
  { symbol: 'SOFI', name: '소파이 (SoFi Technologies)', market: 'US' },
  { symbol: 'BBAI', name: '빅베어 AI (BigBear.ai)', market: 'US' },
  { symbol: 'IONQ', name: '아이온큐 (IonQ Inc)', market: 'US' },
  { symbol: 'INTC', name: '인텔 (Intel Corp)', market: 'US' },
  { symbol: 'QCOM', name: '퀄컴 (Qualcomm Inc)', market: 'US' },
  { symbol: 'TSM', name: 'TSMC (Taiwan Semiconductor)', market: 'US' },
  { symbol: 'LLY', name: '일라이 릴리 (Eli Lilly and Co)', market: 'US' },
  { symbol: 'COST', name: '코스트코 (Costco Wholesale)', market: 'US' },
  { symbol: 'WMT', name: '월마트 (Walmart Inc)', market: 'US' },
  { symbol: 'DIS', name: '디즈니 (Walt Disney Co)', market: 'US' },
  { symbol: 'NKE', name: '나이키 (Nike Inc)', market: 'US' },
  { symbol: 'SBUX', name: '스타벅스 (Starbucks Corp)', market: 'US' },
  { symbol: 'PYPL', name: '페이팔 (PayPal Holdings)', market: 'US' },
  { symbol: 'CRM', name: '세일즈포스 (Salesforce Inc)', market: 'US' },
  { symbol: 'ORCL', name: '오라클 (Oracle Corp)', market: 'US' },
  { symbol: 'BRK.B', name: '버크셔 해서웨이 B (Berkshire Hathaway B)', market: 'US' },
  { symbol: 'SPY', name: 'SPDR S&P 500 ETF (SPY)', market: 'US' },
  { symbol: 'QQQ', name: 'Invesco QQQ Trust (나스닥 100 ETF)', market: 'US' },
  { symbol: 'SOXL', name: 'Direxion 반도체 3X 불 (SOXL)', market: 'US' },
  { symbol: 'SOXS', name: 'Direxion 반도체 3X 베어 (SOXS)', market: 'US' },
  { symbol: 'TQQQ', name: 'ProShares 울트라프로 QQQ 3X (TQQQ)', market: 'US' },
  { symbol: 'SQQQ', name: 'ProShares 울트라프로 숏 QQQ 3X (SQQQ)', market: 'US' },
  { symbol: 'SMH', name: 'VanEck Semiconductor ETF (SMH)', market: 'US' }
];

