export interface StockSuggestion {
  symbol: string;
  name: string;
  market: 'KR';
  price?: number;
}

export const POPULAR_STOCKS: StockSuggestion[] = [
  // 국내 대표 우량 및 주도주 (코스피 / 코스닥)
  { symbol: '005930', name: '삼성전자 (Samsung Electronics)', market: 'KR' },
  { symbol: '000660', name: 'SK하이닉스 (SK hynix)', market: 'KR' },
  { symbol: '373220', name: 'LG에너지솔루션 (LG Energy Solution)', market: 'KR' },
  { symbol: '207940', name: '삼성바이오로직스 (Samsung Biologics)', market: 'KR' },
  { symbol: '005380', name: '현대차 (Hyundai Motor)', market: 'KR' },
  { symbol: '035420', name: 'NAVER (네이버)', market: 'KR' },
  { symbol: '035720', name: '카카오 (Kakao)', market: 'KR' },
  { symbol: '000270', name: '기아 (Kia)', market: 'KR' },
  { symbol: '068270', name: '셀트리온 (Celltrion)', market: 'KR' },
  { symbol: '005490', name: 'POSCO홀딩스 (POSCO Holdings)', market: 'KR' },
  { symbol: '105560', name: 'KB금융 (KB Financial)', market: 'KR' },
  { symbol: '055550', name: '신한지주 (Shinhan Financial)', market: 'KR' },
  { symbol: '006400', name: '삼성SDI (Samsung SDI)', market: 'KR' },
  { symbol: '051910', name: 'LG화학 (LG Chem)', market: 'KR' },
  { symbol: '012330', name: '현대모비스 (Hyundai Mobis)', market: 'KR' },
  { symbol: '028260', name: '삼성물산 (Samsung C&T)', market: 'KR' },
  { symbol: '086790', name: '하나금융지주 (Hana Financial)', market: 'KR' },
  { symbol: '138040', name: '메리츠금융지주 (Meritz Financial)', market: 'KR' },
  { symbol: '034730', name: 'SK (에스케이)', market: 'KR' },
  { symbol: '003550', name: 'LG (엘지)', market: 'KR' },
  { symbol: '247540', name: '에코프로비엠 (Ecopro BM)', market: 'KR' },
  { symbol: '086520', name: '에코프로 (Ecopro)', market: 'KR' },
  { symbol: '196170', name: '알테오젠 (Alteogen)', market: 'KR' },
  { symbol: '028300', name: 'HLB (에이치엘비)', market: 'KR' },
  { symbol: '042700', name: '한미반도체 (Hanmi Semiconductor)', market: 'KR' },
  { symbol: '012450', name: '한화에어로스페이스 (Hanwha Aerospace)', market: 'KR' },
  { symbol: '079550', name: 'LIG넥스원 (LIG Nex1)', market: 'KR' },
  { symbol: '025820', name: '이구산업 (Lee Ku Industrial)', market: 'KR' },
  { symbol: '001520', name: '동양 (Tongyang)', market: 'KR' },
  { symbol: '025560', name: '미래산업 (Mirae Corp)', market: 'KR' },
  { symbol: '004060', name: 'SG세계물산 (SG Global)', market: 'KR' },
  { symbol: '014160', name: '대영포장 (Daeyoung Packaging)', market: 'KR' },
  { symbol: '073240', name: '금호타이어 (Kumho Tire)', market: 'KR' },
  { symbol: '030200', name: 'KT (케이티)', market: 'KR' },
  { symbol: '017670', name: 'SK텔레콤 (SK Telecom)', market: 'KR' },
  { symbol: '032830', name: '삼성생명 (Samsung Life)', market: 'KR' },
  { symbol: '018260', name: '삼성에스디에스 (Samsung SDS)', market: 'KR' },
  { symbol: '010140', name: '삼성중공업 (Samsung Heavy)', market: 'KR' },
  { symbol: '009540', name: 'HD한국조선해양 (HD Korea Shipbuilding)', market: 'KR' },
  { symbol: '329180', name: 'HD현대중공업 (HD Hyundai Heavy)', market: 'KR' },
  { symbol: '010950', name: 'S-Oil (에쓰오일)', market: 'KR' },
  { symbol: '036570', name: '엔씨소프트 (NCSOFT)', market: 'KR' },
  { symbol: '251270', name: '넷마블 (Netmarble)', market: 'KR' },
  { symbol: '263750', name: '펄어비스 (Pearl Abyss)', market: 'KR' },
  { symbol: '293490', name: '카카오게임즈 (Kakao Games)', market: 'KR' },
  { symbol: '352820', name: '하이브 (HYBE)', market: 'KR' },
  { symbol: '069500', name: 'KODEX 200 (코덱스 200)', market: 'KR' },
  { symbol: '122630', name: 'KODEX 레버리지 (KODEX Leverage)', market: 'KR' },
  { symbol: '114800', name: 'KODEX 인버스 (KODEX Inverse)', market: 'KR' },
  { symbol: '252670', name: 'KODEX 200선물인버스2X', market: 'KR' },
  { symbol: '233740', name: 'KODEX 코스닥150레버리지', market: 'KR' },
  { symbol: '251340', name: 'KODEX 코스닥150선물인버스', market: 'KR' },
  { symbol: '000810', name: '삼성화재 (Samsung Fire & Marine)', market: 'KR' },
  { symbol: '015760', name: '한국전력 (KEPCO)', market: 'KR' },
  { symbol: '033780', name: 'KT&G (케이티앤지)', market: 'KR' },
  { symbol: '003670', name: '포스코퓨처엠 (POSCO Future M)', market: 'KR' },
  { symbol: '011200', name: 'HMM (에이치엠엠)', market: 'KR' },
  { symbol: '010130', name: '고려아연 (Korea Zinc)', market: 'KR' }
];
