export interface StockSuggestion {
  symbol: string;
  name: string;
  market: 'KR' | 'US';
}

export const POPULAR_STOCKS: StockSuggestion[] = [
  // KR Stocks
  { symbol: '073240', name: '금호타이어', market: 'KR' },
  { symbol: '005930', name: '삼성전자', market: 'KR' },
  { symbol: '000660', name: 'SK하이닉스', market: 'KR' },
  { symbol: '035420', name: '네이버', market: 'KR' },
  { symbol: '035720', name: '카카오', market: 'KR' },
  { symbol: '005380', name: '현대차', market: 'KR' },
  { symbol: '005935', name: '삼성전자우', market: 'KR' },
  { symbol: '207940', name: '삼성바이오로직스', market: 'KR' },
  { symbol: '006400', name: '삼성SDI', market: 'KR' },
  { symbol: '051910', name: 'LG화학', market: 'KR' },
  { symbol: '000270', name: '기아', market: 'KR' },
  { symbol: '005490', name: 'POSCO홀딩스', market: 'KR' },
  { symbol: '105560', name: 'KB금융', market: 'KR' },
  { symbol: '068270', name: '셀트리온', market: 'KR' },
  { symbol: '003550', name: 'LG', market: 'KR' },
  { symbol: '034730', name: 'SK', market: 'KR' },
  { symbol: '012330', name: '현대모비스', market: 'KR' },
  { symbol: '055550', name: '신한지주', market: 'KR' },
  { symbol: '015760', name: '한국전력', market: 'KR' },
  { symbol: '032830', name: '삼성생명', market: 'KR' },
  { symbol: '000810', name: '삼성화재', market: 'KR' },
  { symbol: '033780', name: 'KT&G', market: 'KR' },
  { symbol: '003670', name: '포스코푸드', market: 'KR' },
  { symbol: '009150', name: '삼성전기', market: 'KR' },
  { symbol: '086790', name: '하나금융지주', market: 'KR' },
  { symbol: '010130', name: '고려아연', market: 'KR' },
  { symbol: '018260', name: '삼성에스디에스', market: 'KR' },
  { symbol: '017670', name: 'SK텔레콤', market: 'KR' },
  { symbol: '011200', name: 'HMM', market: 'KR' },
  { symbol: '010950', name: 'S-Oil', market: 'KR' },
  { symbol: '251270', name: '넷마블', market: 'KR' },
  { symbol: '096770', name: 'SK이노베이션', market: 'KR' },
  { symbol: '090430', name: '아모레퍼시픽', market: 'KR' },
  { symbol: '034220', name: 'LG디스플레이', market: 'KR' },
  { symbol: '036570', name: '엔씨소프트', market: 'KR' },
  { symbol: '003490', name: '대한항공', market: 'KR' },
  { symbol: '030200', name: 'KT', market: 'KR' },
  { symbol: '011070', name: 'LG이노텍', market: 'KR' },
  { symbol: '004020', name: '현대제철', market: 'KR' },
  { symbol: '028260', name: '삼성물산', market: 'KR' },
  
  // US Stocks
  { symbol: 'NVDA', name: '엔비디아', market: 'US' },
  { symbol: 'AAPL', name: '애플', market: 'US' },
  { symbol: 'TSLA', name: '테슬라', market: 'US' },
  { symbol: 'MSFT', name: '마이크로소프트', market: 'US' },
  { symbol: 'GOOGL', name: '알파벳 A', market: 'US' },
  { symbol: 'AMZN', name: '아마존', market: 'US' },
  { symbol: 'META', name: '메타', market: 'US' },
  { symbol: 'AMD', name: 'AMD', market: 'US' },
  { symbol: 'NFLX', name: '넷플릭스', market: 'US' },
  { symbol: 'BRK.B', name: '버크셔 해서웨이 B', market: 'US' },
  { symbol: 'V', name: '비자', market: 'US' },
  { symbol: 'JPM', name: 'JP모건', market: 'US' },
  { symbol: 'WMT', name: '월마트', market: 'US' },
  { symbol: 'MA', name: '마스터카드', market: 'US' },
  { symbol: 'AVGO', name: '브로드컴', market: 'US' },
  { symbol: 'COST', name: '코스트코', market: 'US' },
  { symbol: 'TSM', name: 'TSMC', market: 'US' },
  { symbol: 'LLY', name: '일라이 릴리', market: 'US' },
  { symbol: 'UNH', name: '유나이티드헬스', market: 'US' },
  { symbol: 'PEP', name: '펩시코', market: 'US' },
  { symbol: 'KO', name: '코카콜라', market: 'US' },
  { symbol: 'DIS', name: '디즈니', market: 'US' },
  { symbol: 'NKE', name: '나이키', market: 'US' },
  { symbol: 'INTC', name: '인텔', market: 'US' },
  { symbol: 'PYPL', name: '페이팔', market: 'US' },
  { symbol: 'QCOM', name: '퀄컴', market: 'US' },
  { symbol: 'CRM', name: '세일즈포스', market: 'US' },
  { symbol: 'T', name: 'AT&T', market: 'US' },
  { symbol: 'ABBV', name: '애브비', market: 'US' },
  { symbol: 'SBUX', name: '스타벅스', market: 'US' },
  { symbol: 'BABA', name: '알리바바', market: 'US' },
  { symbol: 'ORCL', name: '오라클', market: 'US' },
  { symbol: 'TXN', name: '텍사스 인스트루먼트', market: 'US' },
  { symbol: 'MCD', name: '맥도날드', market: 'US' },
  { symbol: 'BAC', name: '뱅크 오브 아메리카', market: 'US' },
];
